# -*- coding: utf-8 -*-
"""Check_point_Déployer _un _classificateur _d'images _personnalisées - CORRIGÉ

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UJKeJM6rZgEuw1KRcM2Noz4JkTU5_o1
    
⚠️ CORRECTION: Ligne 104 supprimée (elle écrasait le modèle créé)
"""

!pip install -q kagglehub

import kagglehub

# Download latest version
path = kagglehub.dataset_download("mohitsingh1804/plantvillage")

print("Path to dataset files:", path)

# Vérification

print(os.listdir(path))

# Importation des packages

import tensorflow as tf
import os
import pathlib

from tensorflow.keras.applications import ResNet50
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras import layers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

import seaborn as sns
import numpy as np



import matplotlib.pyplot as plt

# Paramètre

IMG_SIZE = (224, 224)
BATCH_SIZE = 32

# chargement des données

datagen = ImageDataGenerator(
    rescale=1./255
)

# chargement des images d'entrainememnt

train_data = datagen.flow_from_directory(
    os.path.join(path, 'PlantVillage', 'train'),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_data = datagen.flow_from_directory(
    os.path.join(path, 'PlantVillage', 'val'),
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

# Vérificaiion du chargement

class_names = list(train_data.class_indices.keys())
print(class_names)

# création du modèle CNN

model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(IMG_SIZE[0], IMG_SIZE[1],3)),
    layers.MaxPooling2D(2,2),
    layers.Dropout(0.2),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Dropout(0.2),

    layers.Conv2D(128, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Dropout(0.2),


    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),

    layers.Dense(len(class_names), activation='softmax')
])

# Structure du modèle
print("\n Structure du modèle")
model.summary()

# ✅ LIGNE 104 SUPPRIMÉE (elle écrasait le modèle créé):
# model = tf.keras.models.load_model("agrovision_model.keras", compile=False)

# Complation du modèle

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# Entrainememnt du modèle

history = model.fit(
    train_data,
    epochs=10,
    validation_data=val_data
)

# valeur ACCURCY

acc = history.history['accuracy']
val_acc = history.history['val_accuracy']

print(acc)
print(val_acc)

# Courbe ACCURACY

plt.plot(history.history['accuracy'], label='train_acc')
plt.plot(history.history['val_accuracy'], label='val_acc')
plt.legend()
plt.title("Accuracy")
plt.show()

# Valeur LOSS

loss = history.history['loss']
val_loss = history.history['val_loss']

print(loss)
print(val_loss)

# Courbe LOSS

plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.legend()
plt.title("Loss")
plt.show()

# Valeur final ACCURACY et LOSS

final_train_acc = history.history['accuracy'][-1]
final_val_acc = history.history['val_accuracy'][-1]

final_train_loss = history.history['loss'][-1]
final_val_loss = history.history['val_loss'][-1]

print("==== Résultats finaux ==== ")
print(f"Train Accuracy : {final_train_acc:.4f}")
print(f"Validation Accuracy : {final_val_acc:.4f}")
print(f"Train Loss : {final_train_loss:.4f}")
print(f"Validation Loss : {final_val_loss:.4f}")

# Prédictions

predictions = model.predict(val_data)
y_pred = np.argmax(predictions, axis=1)
y_true = val_data.classes

# Matrice

cm = confusion_matrix(y_true, y_pred)

# Courbe Matrice

plt.figure(figsize=(10,8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Prédictions")
plt.ylabel("Vraies classes")
plt.title("Matrice de confusion")
plt.show()

# Rapport de classification

class_names = list(val_data.class_indices.keys())

print(classification_report(y_true, y_pred, target_names=class_names))

# Sauvegarde du modèle
# Utiliser format .keras (moderne et compatible)
model.save("agrovision_model.keras")

print("✅ Modèle sauvegardé avec succès en format .keras !")

# Téléchargé le modèle

from google.colab import files

# Télécharger le fichier .keras
files.download("agrovision_model.keras")
